name: data102

channels:
- defaults

dependencies:
  - beautifulsoup4=4.7.1
  - bokeh=1.3.2
  - cloudpickle=1.2.1
  - coverage=4.5.3
  - cryptography=2.7
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask=2.2.0
  - dask-core=2.2.0
  - decorator=4.4.0
  - distributed=2.2.0
  - flake8=3.7.7
  - graphviz=2.40.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - html5lib=1.0.1
  - hypothesis=4.32.2
  - ipykernel=5.1.1
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - joblib=0.13.2
  - jupyter=1.0.0
  - jupyterlab=1.0.2
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - lxml=4.3.4
  - mako=1.0.10
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - networkx=2.3
  - nodejs=10.13.0
  - notebook=6.0.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - pandas=0.25.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - patsy=0.5.1
  - pep8=1.7.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.1.1
  - plotly=4.0.0
  - pluggy=0.12.0
  - prompt_toolkit=2.0.9
  - pyflakes=2.1.1
  - pygments=2.4.2
  - pytest=5.0.1
  - python=3.7.3
  - python-editor=1.0.4
  - python-oauth2=1.1.1
  - requests=2.22.0
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - seaborn=0.9.0
  - statsmodels=0.10.1
  - sqlalchemy=1.3.5
  - sympy=1.4
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.2
  - tqdm=4.32.1
  - widgetsnbextension=3.5.0
  - xarray=0.12.1
  - yaml=0.1.7
  - pip:
    - cufflinks==0.16
    - plotly_express==0.4.0
    - tweepy==3.8.0
    - ipympl==0.3.3
    - nbzip==0.1.0
    - nbgitpuller==0.7.0
    - jupyter-contrib-nbextensions==0.5.1
    # We need JHub installed via pip as there's a conflict with nodejs on the
    # conda repos
    - jupyterhub==0.9.6
    - jassign==0.0.7
    - okpy==1.14.15
    - nbresuse==0.3.2
    # nbconvert 5.4.0 with pdf export fix
    #- git+https://github.com/ryanlovett/nbconvert.git@16fe302
