nfsMounter:
  enabled: false

nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.94.73.146
    shareName: userhomes

jupyterhub:
  hub:
    services:
      gofer_nb:
        url: http://35.239.20.122:10101
  auth:
    type: lti
    admin:
      users:
        - 6f3e32e2b27f0fa7c7bfd6e6c5fc9073
        - 574b83d902c693a3ebe45fac88e498e8
        - dab2902831a95eb786a1f52b14717b38
        - 2003753d84d84db85790fa8de0739eb4
        - 5b9e64abdebeca5d617822381744744b
        - a7b92e1bffedf669c8301f76e617f255
        - bce998e3f793c84d635d63b0122c662d
        - 4da3ae20c3f95786fce26c8b92d37a60
        - ba2c4ab02e0a25755ce903d5c376b7e2
        - 64b9b0b2fde14942b20fe960002b38d9
        - 9cb1fbfa7af6472dc8d8dddc28b905be
        - e39a60f081cdfd06347d83df61af4c38
        - 5eac02c99456373adc10942c9e9adaf1
        - add4f14e61b549bb26aaac1ec05e97a3
        - 6edae5baf9b08066df2ca99ecc2c1bf3
        - 23f3ac405063c21b23275504ca45ab2b
        - 630b33bc007fc68a4912b90d85443224
        - e3a956bffbae67d42744ef08be58a48e
        - 030777d951ba972876eaab81c3bceb21
        - 461ee9f934be0a3079ba12ecc066939b
        - 780e0c299d28f5ab0d505ec8dfffd898
        - ccd399c54550718cafa19b4a2e230bfc
        - 25a7599135b2bc244ba0e511ec988371
        - 0b3a7d0def967c26e030cc3071d57cde
        - 4a3686977e73987429ffed1239fff3c1
        - d921b4caaa1fe484094618ead010445d
        - 552c15a76d0bc7b546f5baef4310b7f4
  singleuser:
    initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "home/{username}"
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "home/{username}"
    memory:
      guarantee: 256M
      limit: 1G
    image:
      name: gcr.io/data8x-scratch/data8x-user-image
