name: stat159-s23

channels:
  - conda-forge

dependencies:
  - python==3.10.8
  
  - altair==4.2.0
  - beautifulsoup4==4.11.1
  - black==22.12.0
  - bokeh==3.0.3
  - bqplot==0.12.36
  - cartopy==0.21.1
  - coverage==7.0.5
  - cython==0.29.33
  - dask==2022.11.0
  - dask-labextension==6.0.0
  - fortran-magic==0.7
  - gh-scoped-creds==4.1
  - h5netcdf==1.1.0
  - h5py==3.7.0
  - hdf4==4.2.15
  - hdf5==1.12.2
  - intake==0.6.6
  - intake-esm==2022.9.18
  - intake-xarray==0.6.1
  - ipycanvas==0.13.1
  - ipydatagrid==1.1.14
  - ipympl==0.9.2
  - ipyparallel==8.4.1
  - jupyter-book==0.13.1
  - jupyter-repo2docker==2022.10.0
  - jupyter-resource-usage==0.7.0
  - jupyter_bokeh==3.0.5
  - jupyterlab==3.5.2
  - jupyterlab-drawio==0.9.0
  - jupyterlab-favorites==3.1.1
  - jupyterlab-geojson==3.3.1
  - jupyterlab-git==0.41.0
  - jupyterlab-link-share==0.2.5
  - jupyterlab-variableinspector==3.0.9
  - jupyterlab_pygments==0.2.2
  - jupyterlab_widgets==3.0.5
  - jupytext==1.14.4
  - matplotlib==3.6.3
  - matplotlib-inline==0.1.6
  - mock==5.0.1
  - nbdime==3.1.1
  - networkx==3.0
  - numba==0.56.4
  - numpy==1.23.5
  - pandas==1.5.2
  - pandoc==2.19.2
  - pandocfilters==1.5.0
  - pep8==1.7.1
  - pillow==9.4.0
  - pip==22.3.1
  - plotly==5.12.0
  - pooch==1.6.0
  - prettytable==3.6.0
  - pyarrow==10.0.1
  - pypdf2==2.11.1
  - pytables==3.7.0
  - pytest==7.2.1
  - pytest-cov==4.0.0
  - pytest-notebook==0.6.1
  - requests==2.28.2
  - ruyaml==0.91.0
  - scikit-image==0.19.3
  - scikit-learn==1.2.0
  - scipy==1.10.0
  - seaborn==0.12.2
  - sphinx-jupyterbook-latex==0.4.7
  - sqlparse==0.4.3
  - statsmodels==0.13.5
  - sympy==1.11.1
  - tqdm==4.64.1
  - xarray==2022.12.0
  - xlrd==2.0.1

  # # Packages needed only on the hub (mostly linux)
  # # If installing this environment on a mac, comment these out
  - git=2.39.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - syncthing=1.23.0
  - micro=2.0.8
  - websockify=0.11.0
  - python-pdfkit==1.0.0 

  - pip:
    - jupyter-desktop-server==0.1.3
    - ipython-sql==0.4.1
