name: stat159-s23

channels:
  - conda-forge

dependencies:
  - python==3.10.8
  - nodejs=18

  - altair==4.2.2
  - beautifulsoup4==4.11.1
  - black==22.12.0
  - bokeh==2.4.3
  - bqplot==0.12.36
  - cartopy==0.21.1
  - coverage==7.0.5
  - cython==0.29.33
  - dask==2023.1.1
  - dask-labextension==6.0.0
  - fortran-magic==0.7
  - gh-scoped-creds==4.1
  - h5netcdf==1.1.0
  - h5py==3.7.0
  - hdf4==4.2.15
  - hdf5==1.12.2
  - intake==0.6.6
  - intake-esm==2022.9.18
  - intake-xarray==0.6.1
  - ipycanvas==0.13.1
  - ipydatagrid==1.1.14
  - ipympl==0.9.2
  - ipyparallel==8.4.1
  - ipykernel==6.21.2
  - ipywidgets==8.0.4

  # Temporarily disable jupyter-book as build isn't resolving.
  # We neeed https://github.com/executablebooks/jupyter-book/pull/1842
  # to be merged before we can add it back.
  #- jupyter-book==0.13.2

  - jupyter-resource-usage==0.7.1
  - jupyter_bokeh==3.0.5
  - jupyter_server==2.2.1
  - jupyterlab==3.6.1
  - jupyterlab-drawio==0.9.0
  - jupyterlab-favorites==3.1.1
  - jupyterlab-geojson==3.3.1
  - jupyterlab-git==0.41.0
  - jupyterlab-link-share==0.2.5
  - jupyterlab-variableinspector==3.0.9
  - jupyterlab-myst==1.1.0
  - jupyterlab_pygments==0.2.2
  - jupyterlab_server==2.19.0
  - jupyterlab_widgets==3.0.5
  - jupytext==1.14.4
  - mamba==1.2.0
  - matplotlib==3.6.3
  - matplotlib-inline==0.1.6
  - mock==5.0.1
  - nbconvert==6.5.3
  - nbdime==3.1.1
  - nbgitpuller==1.1.1
  - networkx==3.0
  - numba==0.56.4
  - numpy==1.23.5
  - pandas==1.5.3
  - pandoc==2.19.2
  - pandocfilters==1.5.0
  - pep8==1.7.1
  - pillow==9.4.0
  - pip==22.3.1
  - plotly==5.12.0
  - pooch==1.6.0
  - prettytable==3.6.0
  - pyarrow==10.0.1
  - pypdf2==2.11.1
  - pytables==3.7.0
  - pytest==7.2.1
  - pytest-cov==4.0.0
  - pytest-notebook==0.6.1
  - requests==2.28.2
  - ruyaml==0.91.0
  - scikit-image==0.19.3
  - scikit-learn==1.2.0
  - scipy==1.10.0
  - seaborn==0.12.2
  - sphinx-jupyterbook-latex==0.5.2
  - sqlparse==0.4.3
  - statsmodels==0.13.5
  - sympy==1.11.1
  - tk==8.6.12
  - tornado==6.2.0
  - tqdm==4.64.1
  - xarray==2023.1.0
  - xlrd==2.0.1

  # Packages that could be installed via the system package manager
  # (apt, homebrew, etc) but we bring them through here for better
  # reproducibility
  - git==2.39.1
  - pandoc==2.19.2
  - pandocfilters==1.5.0

  # Packages needed only on the hub (mostly linux)
  # If installing this environment on a personal machine, 
  # comment these out (but not the pip section below)
  - syncthing==1.23.0
  - micro==2.0.8
  - websockify==0.11.0
  - python-pdfkit==1.0.0 

# Packages not available on conda-forge, installed through pip
  - pip:
    - ipython-sql==0.4.1
    
    # Packages needed only on the hub (mostly linux)
    # If installing this environment on a personal machine, 
    # comment these out
    - jupyter-remote-desktop-proxy==1.0.0
    # syncthing for dropbox-like functionality
    - jupyter-syncthing-proxy==1.0.3
    - git+https://github.com/berkeley-dsep-infra/tmpystore.git@84765e1
