jupyterhub:
  proxy:
    # service:
      # FIXME: make the IP static in google cloud console so we won't lose it
      # then specify it here so if we redeploy we get the same stuff
      # loadBalancerIP: <IP of genomics.datahub.berkeley.edu
    https:
      hosts:
        - genomics.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
