dependencies:
  - python==3.9.*
  - pip==20.2.*
  - matplotlib==3.5.2
  - pandas==1.4.3
  - scipy==1.9.0
  - numpy==1.23.1

  # Visual Studio Code!
  - jupyter-vscode-proxy

  - pip:
    - nbforms==0.5.1
    - nbconvert==6.5.1
    - nbformat==5.2.0
    - datascience==0.17.5
# For grading
    - gofer-submit==0.5.1
    - -r infra-requirements.txt
