dependencies:
- python=3.10.*
- pip=23.1.*
- nodejs=18.*

- jupyter-server-proxy==4.0.0
- jupyter-rsession-proxy==2.2.0

- syncthing==1.23.5
- pyppeteer==1.0.2

# for nbconvert
- pandoc==3.1.3

# for jupyter-tree-download
- zip==3.0
