dependencies:
- nodejs==230.9.0
- pip==22.3.1
- python==3.10.13
- requests==2.31.0

- syncthing==1.18.6

# from requirements.txt
- matplotlib==3.7.2

# Required for issue #3057
- xlrd==2.0.1

# For https://github.com/berkeley-dsep-infra/datahub/issues/3079
- websockify
- pip:
  - jupyter-desktop-server
  - otter-grader==3.1.4
