dependencies:
- jupyter-server-proxy==4.1.1
- nodejs==20.8.1
- pip==22.3.1
- python==3.10.13
- requests==2.31.0

- syncthing==1.18.6

# bug w/notebook and traitlets: https://github.com/jupyter/notebook/issues/7048
- traitlets=5.9.*

# from requirements.txt
- matplotlib==3.7.2

# Required for issue #3057
- xlrd==2.0.1

# For https://github.com/berkeley-dsep-infra/datahub/issues/3079
- websockify
- pip:
  - notebook==7.0.7
  - jupyter-desktop-server
  - otter-grader==3.1.4
  # for notebook exporting
  - nbconvert==7.6.0
  - nb2pdf==0.6.2
  - nbpdfexport==0.2.1
