name: base
channels:
  - conda-forge
dependencies:
  - coverage
  - ipympl=0.4.1
  - ipywidgets=7.5.1
  - jupyterlab=1.2.5
  - matplotlib=3.1.2
  - nodejs=13.7.0
  - numpy=1.17.5
  - pandas=0.25.3
  - pandoc=2.9.1.1
  - pip=20.0.1
  - plotly=4.5.0
  - psutil=5.6.7
  - python=3.7.6
  - pyyaml=5.3
  - requests
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=45.1.0
  - statsmodels=0.11.0
  - tqdm
  - notebook=6.0.0
  - pip:
    - jassign==0.0.7
    - linalg_for_datasci==1.2.2
    - nbgitpuller==0.8.0
    - nbresuse==0.3.3
    - okpy==1.14.19
    - jupyterlab_latex
