name: data100
channels:
- defaults
dependencies:
- attrs=17.3.0
- beautifulsoup4=4.6.0
- bleach=2.1.2
- chardet=3.0.4
- coverage=4.4.2
- cryptography=2.1.4
- cycler=0.10.0
- dask=0.16.1
- decorator=4.2.1
- entrypoints=0.2.3
- expat=2.2.5
- flake8=3.5.0
- html5lib=1.0.1
- hypothesis=3.38.5
- ipykernel=4.7.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.1.0
- jedi=0.11.1
- joblib=0.11
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.1
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- lxml=4.1.1
- matplotlib=2.1.1
- mistune=0.8.3
- nbconvert=5.3.1
- nbformat=4.4.0
- networkx=2.0
- notebook=5.4.1
- numpy=1.12.1
- pandas=0.22
- pandoc=1.19.2.1
- pandocfilters=1.4.2
- patsy=0.5.0
- pcre=8.41
- pep8=1.7.1
- pickleshare=0.7.4
- pip=9.0.1
- plotly=2.2.2
- pluggy=0.6.0
- prompt_toolkit=1.0.15
- protobuf=3.4.1
- py=1.5.2
- pyflakes=1.5.0
- pygments=2.2.0
- pylint=1.8.1
- pyparsing=2.2.0
- pytables=3.4.4
- pytest=3.3.2
- python=3.6.4
- python-dateutil=2.6.1
- pytz=2017.3
- pyzmq=16.0.3
- requests=2.18.4
- scikit-image=0.13.0
- scikit-learn=0.19.1
- scipy=1.0.0
- seaborn=0.9.0
- setuptools=38.4.0
- simplegeneric=0.8.1
- sip=4.18.1
- six=1.11.0
- sqlalchemy=1.2.1
- sqlite=3.20.1
- statsmodels=0.8.0
- sympy=1.1.1
- tensorflow=1.1.0
- toolz=0.9.0
- tornado=4.5.3
- traitlets=4.3.2
- widgetsnbextension=3.1.0
- xarray=0.10.0
- xz=5.2.3
- zeromq=4.2.2
- pip:
  - colorlover==0.2.1
  - cufflinks==0.12.1
  - jupyterlab==0.31.12
  - oauthlib==2.0.6
  - requests-oauthlib==0.8.0
  - tweepy==3.5.0
  
