name: data100
channels:
- defaults
dependencies:
- attrs=17.3.0
- beautifulsoup4=4.6.0
- bleach=2.1.2
- chardet=3.0.4
- coverage=4.4.2
- cryptography=2.1.4
- cycler=0.10.0
- dask=0.16.1
- decorator=4.2.1
- entrypoints=0.2.3
- expat=2.2.5
- flake8=3.5.0
- html5lib=1.0.1
- hypothesis=3.38.5
- ipykernel=4.7.0
- ipython=7.2.0
- ipython_genutils=0.2.0
- ipywidgets=7.4.2
- jedi=0.11.1
- joblib=0.11
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.3
- jupyter_console=6.0.0
- jupyter_core=4.4.0
- lxml=4.1.1
- matplotlib=3.0.1
- mistune=0.8.3
- nbformat=4.4.0
- networkx=2.0
- nodejs=10.13.0
- notebook=5.7.8
- numpy=1.15.4
- oauthlib=2.1.0
- pandas=0.23.4
- pandoc=1.19.2.1
- pandocfilters=1.4.2
- patsy=0.5.0
- pcre=8.42
- pep8=1.7.1
- pickleshare=0.7.4
- pip=9.0.1
- plotly=2.2.2
- pluggy=0.6.0
- prompt_toolkit=2.0.7
- protobuf=3.6.1
- py=1.5.2
- pyflakes=1.5.0
- pygments=2.2.0
- pylint=1.8.1
- pyparsing=2.2.0
- pytest=3.3.2
- python=3.6.4
- python-dateutil=2.6.1
- pytz=2017.3
- pyzmq=17.1.2
- requests=2.20.1
- requests-oauthlib=1.0.0
- scikit-image=0.13.0
- scikit-learn=0.19.1
- scipy=1.1.0
# see below for seaborn version
#- seaborn=0.9.0
- setuptools=38.4.0
- simplegeneric=0.8.1
- sip=4.19.8
- six=1.11.0
- sqlalchemy=1.2.1
- sqlite=3.25.3
- statsmodels=0.8.0
- sympy=1.1.1
- tensorflow=1.12.0
- toolz=0.9.0
- tornado=5.1.1
- traitlets=4.3.2
- widgetsnbextension=3.4.2
- xarray=0.11.0
- xz=5.2.4
- zeromq=4.2.5
- graphviz=2.40.1
- pip:
  - colorlover==0.2.1
  - cufflinks==0.12.1
  - jupyterlab==0.35.4
  - tweepy==3.5.0
  - nbzip==0.1.0
  - nbgitpuller==0.6.1
  - jupyter-contrib-nbextensions==0.5.1
  - psycopg2==2.7.6.1
  - jupyterhub==0.9.2
  - jupyter-server-proxy==1.0.0
  - jassign==0.0.7
  - okpy==1.13.11
  - tqdm==4.29.1
  - nbresuse==0.3.1
  # nbconvert 5.4.0 with pdf export fix
  - git+https://github.com/ryanlovett/nbconvert.git@16fe302
  # Install seaborn via pip, it will update pandas along the way
  - seaborn==0.9.0
  - graphviz==0.10.1
  - ray[debug]==0.6.5
