name: data100-FA23

channels:
- conda-forge
- pytorch

dependencies:
- python==3.11.*
- git==2.46.0
- gh-scoped-creds==4.1
- jupyter-resource-usage==1.1.0
- jupyterhub==4.1.6
- jupyterlab==4.2.5
- jupyterlab-favorites==3.0.0
- jupyterlab-git==0.50.1
- jupyterlab_server==2.27.3
- jupyterlab_widgets==3.0.8
- jupyter_server==2.27.3
# pulled in by ottr, if not pinned to 1.16.2, 1.16.3 causes DH-323
- jupytext==1.16.2
- nbgitpuller==1.2.1
- notebook==7.2.2
- folium==0.14.0
- h5netcdf==1.0.2
- ipywidgets==8.0.7
- jupysql==0.8.0
- jupyter-archive==3.4.0
- matplotlib==3.7.1
- mdit-py-plugins==0.4.0
- numpy==1.24.2
- pandas==2.0.2
- plotly==5.13.1
- requests==2.28.2
- scikit-image==0.19.3
- scikit-learn==1.2.2
- scipy==1.10.1
- seaborn==0.12.2
- statsmodels==0.14.0
- tensorflow-cpu==2.12.1
- sqlalchemy==2.0.16
- mlxtend==0.23.0
# Spring 2024 data 100
- pytorch==2.1.2
- cpuonly==2.0
- transformers==4.37.1
# Spring 2024 table demos
- lxml==5.1.0
# Spring 2024 Econ 148 Packages
- geopandas==0.14.2
- geopy==2.4.1
- lifelines==0.27.8
- pycountry==22.3.5
- pip
- pip:
  - ipywidgets==8.0.7
  # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
  # - jupyter_collaboration==1.0.1
  - nbconvert[webpdf]
  #  - pyppeteer==2.0.0
  - pytest-notebook==0.8.1
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - ydata-profiling==4.6.4
  - otter-grader==5.4.0
  - duckdb==0.10.1
  - duckdb_engine==0.11.2
