name: data100-FA23

channels:
- conda-forge

dependencies:
- python==3.11.0
# - syncthing==1.20.4
- git==2.39.1
# - altair==5.0.1
# - beautifulsoup4==4.11.1
# - black==22.6.0
# - bokeh==2.4.3
# - bqplot==0.12.34
# - cartopy==0.21.0
# - coverage==7.2.2
# - cython==0.29.32
# - distributed==2023.6.0
# - fortran-magic==0.7
# - graphviz==8.0.3
# - python-graphviz==0.20.1
# - h5netcdf==1.0.2
# - h5py==3.7.0
# - hdf4==4.2.15
# - hdf5==1.12.2
# - intake==0.6.5
# - intake-esm==2021.8.17
# - intake-xarray==0.6.0
# - ipycanvas==0.12.1
# - ipydatagrid==1.1.12
# - ipympl==0.9.2
# - ipyparallel==8.4.1
# - jsonschema==4.17.3
# - jupyter-book==0.15.1
- jupyter-resource-usage==1.0.0
# - jupyter_bokeh
- jupyterlab==4.0.4
- jupyterlab-favorites==3.0.0
# - jupyterlab-geojson==3.2.0
# - jupyterlab-variableinspector==3.0.9
# - jupyterlab_pygments==0.2.2
- jupyterlab_server==2.23.0
- jupyterlab_widgets==3.0.8
- jupyter_server==2.7.0
# - matplotlib==3.7.1
# - matplotlib-inline==0.1.6
# - mock==4.0.3
# - nbclassic==1.0.0
# - nbdime==3.1.1
- nbgitpuller==1.1.1
# - networkx==2.8.6
- notebook==7.0.2
# - numba==0.57.0
# - numpy==1.24.2
# - pandas==2.0.2
# - pandoc==2.12
# - pandocfilters==1.5.0
# - pep8==1.7.1
# - pillow==9.2.0
# - plotly==5.13.1
# - pooch==1.6.0
# - prettytable==3.4.1
# - pyarrow==9.0.0
# - pypdf2==2.10.4
# - pytables==3.7.0
# - pytest==7.1.2
# - pytest-cov==3.0.0
# - python-pdfkit==1.0.0
# - requests==2.28.2
# - scikit-image==0.19.3
# - scikit-learn==1.2.2
# - scipy==1.10.1
# - seaborn==0.12.2
# - sphinx-jupyterbook-latex==0.5.2
# - sqlparse==0.4.3
# - statsmodels==0.14.0
# - sympy==1.10.1
# - tornado==6.2.0
# - tqdm==4.64.0
# - xarray==2023.5.0
# - xlrd==2.0.1
# - micro==2.0.8
# - websockify==0.11.0
# - folium==0.14.0
- folium==0.14.0
- h5netcdf==1.0.2
- ipywidgets==8.0.7
- jupysql==0.8.0
- jupyterlab==4.0.4
- matplotlib==3.7.1
- mdit-py-plugins==0.4.0
- numpy==1.24.2
- otter-grader==5.1.1
- pandas==2.0.2
- plotly==5.13.1
- requests==2.28.2
- scikit-image==0.19.3
- scikit-learn==1.2.2
- scipy==1.10.1
- seaborn==0.12.2
- statsmodels==0.14.0
- tensorflow-cpu==2.12.0
- sqlalchemy==2.0.16
- pip
- pip:
  # - -r infra-requirements.txt
  - jupysql==0.8.0
  - ipywidgets==8.0.7
  # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
  # - jupyter_collaboration==1.0.1
  - jupyterhub==4.0.1
  - nbconvert==7.6.0
  - pytest-notebook==0.8.1
