name: astrods

channels:
- conda-forge
- pytorch

dependencies:
- python=3.11.*
- jupyter-server-proxy>=4.3
- git==2.39.1
- jupyter-resource-usage==1.0.0
- jupyterlab==4.0.11
- jupyterlab-favorites==3.0.0
- jupyterlab_server==2.23.0
- jupyterlab_widgets==3.0.8
- jupyter_server==2.7.0
- nbgitpuller==1.2.1
- notebook==7.0.7
# A linux desktop environment
- websockify
- numpy>=2.1.0
- numexpr>=2.10.0
- matplotlib==3.9.*
- graphviz>=2.50.0
- psycopg2==2.9.*
- pytorch
- torchvision
- pytorch-lightning
- cartopy
- cpuonly
- pandas>=2.2.2
- protobuf
- jupysql
- mpich
- mpi4py
- mkl
- mkl-service
- netcdf4>=1.6
- scikit-learn==1.5.*
- scikit-image==0.24.*
- scipy==1.14.*
- tensorflow-cpu==2.17.0
- tensorflow==2.17.0
- jax>=0.4.31
- jaxlib>=0.4.31
- cython==3.0.11
- pip

- pip:
  - opencv-python>=4.5.5.62
  - nose2>=0.10.0
  - sympy
  - beautifulsoup4
  - tqdm
  - corner==2.2.*
  - dask>=2024.8.1 
  - dask-ml>=2024.4.4
  - distributed>=2024.8.1
  - SQLAlchemy>=2.0.32 
  - xarray>=2024.7.0
  - nltk>=3.9.1
  - seaborn>=0.13.2
  - bqplot>=0.12.43
  - astroquery>=0.4.7
  - astropy>=6.1.2
  - dustmaps>=1.0.13
  - pyvo>=1.5.2
  - joblib==1.4.2
  - pymc>=5.16.2
  - requests>=2.32.3
  - ipycanvas
  - altair>=5.4.0
  - vega3>=0.13.0
  - pytz>=2024.1
  - lightkurve
  - ipyparallel
  - line_profiler>=4.1.3
  - snakeviz>=2.2.0
  - memory_profiler>=0.61.0
  - flask>=3.0.3
  - stsci.tools>=4.1.0
  - gensim>=4.3.3
  - tweet-preprocessor
  - pyLDAvis==3.4.1
  - umap-learn>=0.5.6
  - pydot>=3.0.1
  - TPOT>=0.12.2
  - tables>=3.10.1
  - aiohttp>=3.10.4
  - watermark
  - autopep8
  - vega_datasets
  - vega
  - pandas-bokeh
  - pythreejs
  - ipywidgets
  - ipyvolume
  - urllib3
  - six
  - ipython
  - notebook
  - click
  - fire
  - pycodestyle
  - flake8
  - tdtax>=0.1.6
#  - nb_black
  - pycodestyle_magic
  - twine
  - otter-grader>=3.1.4
  # for notebook exporting
  - nbconvert[webpdf]
  - nb2pdf==0.6.2
  - nbpdfexport==0.2.1
  - pytest-notebook==0.8.1
  - jupyter-tensorboard>=0.2.0