channels:
- conda-forge

# Almost all libraries should be added in requirements.txt
# Only libraries *not* available in PyPI should be here
dependencies:
- python=3.9.*
#adding math functionality (not sure what should be here and what should be in PyPI) 
- matplotlib


# Needed for linux desktop environment
- websockify

- qgis=3.22.*

# Maybe needed for qgis? https://github.com/conda-forge/qgis-feedstock/issues/263
- pyopencl

- pip
- pip:
# For desktop environment
  - jupyter-desktop-server==0.1.3
  - -r infra-requirements.txt
  
  #needed for math functions
  - scipy
  - mpld3
