dependencies:
- appmode==0.9.0
- ipywidgets==8.1.2
- jupyter-archive==3.4.0
- jupyter-resource-usage==1.0.1
- jupyter-server-proxy==4.1.1
- jupyter-rsession-proxy==2.2.0
- jupyter-syncthing-proxy==1.0.3
- jupyterhub==4.0.2
- jupyterlab==4.0.11
- nbgitpuller==1.2.0
- notebook==7.0.7
# bug w/notebook and traitlets: https://github.com/jupyter/notebook/issues/7048
- traitlets==5.9.0
- syncthing==1.27.3
- pip:
  - git-credential-helpers==0.2
  - jupyter-shiny-proxy==1.1
  - otter-grader==2.2.7
  # Measure popularity of different packages in our hubs
  # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  #- git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
