project:
  type: website
  resources:
    - "CNAME"

website:
  navbar:
    title: "DataHub"
    search: true
    logo: datahub.svg
    background: light
    tools:
      - icon: github
        href: https://github.com/berkeley-dsep-infra/datahub
    left:
      - text: "Using DataHub"
        href: users/features.qmd
      - text: "Contributing"
        href: admins/pre-reqs.qmd
      - text: "Admin Tasks"
        href: admins/howto/preview-local.qmd
      - text: "Policy"
        href: policy/create_policy.qmd
  page-navigation: true
  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: "Using DataHub"
        contents:
          - users/services.qmd
          - users/private-repo.qmd
          - users/hubs.qmd
          - users/authentication.qmd
      - section: "Contributing to DataHub"
        contents:
          - admins/pre-reqs.qmd
          - admins/structure.qmd
          - admins/storage.qmd
          - admins/cluster-config.qmd
          - admins/credentials.qmd
          - section: "Common Administrator Tasks"
            contents:
              - admins/howto/preview-local.qmd
              - admins/howto/dns.qmd
              - admins/howto/core-pool.qmd
              - admins/howto/new-hub.qmd
              - admins/howto/rebuild-hub-image.qmd
              - admins/howto/rebuild-postgres-image.qmd
              - admins/howto/new-image.qmd
              - admins/howto/new-packages.qmd
              - admins/howto/course-config.qmd
              - admins/howto/calendar-scaler.qmd
              - admins/howto/prometheus-grafana.qmd
              - admins/howto/remove-users-orm.qmd
              - admins/howto/delete-hub.qmd
              - admins/howto/clusterswitch.qmd
              - admins/howto/github-token.qmd
              - admins/howto/google-sheets.qmd
      - section: "Policy"
        contents:
          - policy/create_policy.qmd
          - policy/policy_create_hubs.qmd
          - policy/policy_deploy_mainhubs.qmd
          - policy/principles.qmd
      - href: incidents/index.qmd
        text: "Incident Reports"

format:
  html:
    theme: book
    #title-block-banner: datahub.svg
    navbar:
      left:
        - "UC Berkeley DataHub Documentation"
      right:
        - icon: github
          href: https://github.com/berkeley-dsep-infra/datahub
    footer:
      copyright: "2024, Division of Data Sciences Technical Staff"
      nav:
        - title: UC Berkeley DataHub
          url: https://cdss.berkeley.edu/datahub
        - title: Project Jupyter
          url: https://jupyter.org
