dependencies:
- python=3.11
- pip=23.2.*
- jupyter-server-proxy==4.1.2
- jupyter-rsession-proxy==2.2.0
- jupyterlab-myst==2.0.2
- syncthing==1.25.0
- pyppeteer==1.0.2

# for nbconvert
- pandoc==3.1.3

# for jupyter-tree-download
- zip==3.0

# bug w/notebook and traitlets: https://github.com/jupyter/notebook/issues/7048
- traitlets=5.9.*
- pip:
  - -r infra-requirements.txt
  - jupyter-shiny-proxy==1.1
